version: "3.5"

services:
    mqtt_broker:
      image: eclipse-mosquitto
    tsdb:
      image: influxdb:alpine
      ports:
        - "8086:8086"
      environment:
        - INFLUXDB_HTTP_AUTH_ENABLED=true
        - INFLUXDB_ADMIN_USER=devnet
        - INFLUXDB_ADMIN_PASSWORD=create
        - INFLUXDB_DB=embrace
    tsdb_graphs:
      image: chronograf:alpine
      depends_on:
        - tsdb
    graphdb:
      image: arangodb/arangodb
    web:
      build: ./web
      image: embrace/web
      depends_on:
        - sync
    sync:
      build: ./sync
      image: embrace/sync
      depends_on:
        - mqtt_broker
        - tsdb
        - graphdb
    simulator:
      build: ./simulator
      image: embrace/simulator
      depends_on:
        - sync
